// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA60QHf4TRpgwHuS1TqsJoRTB-EYUjKm2c',
    appId: '1:1352022264:web:dc35c46926b0148245230d',
    messagingSenderId: '1352022264',
    projectId: 'login-signup-7faeb',
    authDomain: 'login-signup-7faeb.firebaseapp.com',
    storageBucket: 'login-signup-7faeb.firebasestorage.app',
    measurementId: 'G-HP8S577MRH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-1zo4ZO08fZc2u1dh3t4BG-6csh6zcTE',
    appId: '1:1352022264:android:2cb4be67d8c08e7045230d',
    messagingSenderId: '1352022264',
    projectId: 'login-signup-7faeb',
    storageBucket: 'login-signup-7faeb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKqoLaK0YlF8HENG4mlPh82Bi3uqg2U7Q',
    appId: '1:1352022264:ios:46a419946dbda5ec45230d',
    messagingSenderId: '1352022264',
    projectId: 'login-signup-7faeb',
    storageBucket: 'login-signup-7faeb.firebasestorage.app',
    iosBundleId: 'com.example.loginSignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKqoLaK0YlF8HENG4mlPh82Bi3uqg2U7Q',
    appId: '1:1352022264:ios:46a419946dbda5ec45230d',
    messagingSenderId: '1352022264',
    projectId: 'login-signup-7faeb',
    storageBucket: 'login-signup-7faeb.firebasestorage.app',
    iosBundleId: 'com.example.loginSignup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA60QHf4TRpgwHuS1TqsJoRTB-EYUjKm2c',
    appId: '1:1352022264:web:2d4b78f2243fdd2c45230d',
    messagingSenderId: '1352022264',
    projectId: 'login-signup-7faeb',
    authDomain: 'login-signup-7faeb.firebaseapp.com',
    storageBucket: 'login-signup-7faeb.firebasestorage.app',
    measurementId: 'G-HJ4YVFZXKM',
  );
}
